name: microbiotAMR 
channels:
  - conda-forge
  - bioconda
  - hcc
  - defaults
dependencies:
  - emu
  - python 
  - fastp
  - chopper
  - resistomeanalyzer
  - porechop
  - panadas
  - numpy
  - crispy
  - termcolor
  - tqdm
  - pip
  - pip: 
  
